/** Design reminder: Registry metadata powers one connected business neighborhood, never duplicate hard-coded game cards. */
export const GAME_IDS = [
  "coin", "needs", "sorter", "budget", "savings", "change", "detective", "discount", "cashflow", "maze", "lemonade", "snack", "tshirt", "pet", "cafe", "adagency", "customerquest", "salesmaster", "brandbuilder", "marketingmix", "investisland", "riskradar", "portfolioquest", "compoundmtn", "scamdetective", "timetycoon", "teambuilder", "supplychain", "inventorymaster", "businesscrisis", "ideafactory", "productlab", "prototyperush", "customerfeedback", "innovationchallenge", "negotiationarena", "teamcaptain", "dealmaker", "communicationlab", "leadershipquest", "marketwars", "strategyempire", "competitorhunt", "growthengine", "businesstycoon", "salesmasterten", "marketingmachine", "ecommercerush", "pitchbattle", "startuplaunch",
] as const;

export type GameId = (typeof GAME_IDS)[number];

export type GameDefinition = {
  id: GameId;
  number: string;
  icon: "coins" | "shapes" | "piggy" | "wallet" | "target" | "receipt" | "search" | "badge" | "store" | "route";
  age: string;
  duration: string;
  titleKey: string;
  shortKey: string;
  objectiveKey: string;
  skillKey: string;
  accent: string;
  image?: string;
};

export const GAME_REGISTRY: GameDefinition[] = [
  { id: "coin", number: "01", icon: "coins", age: "7–10", duration: "2–4", titleKey: "games.coin.title", shortKey: "games.coin.short", objectiveKey: "games.coin.objective", skillKey: "games.coin.skill", accent: "#ff6b4a", image: "/manus-storage/profitspatrol-coin-catcher-scene_1297e504.png" },
  { id: "needs", number: "02", icon: "shapes", age: "7–12", duration: "2–4", titleKey: "games.needs.title", shortKey: "games.needs.short", objectiveKey: "games.needs.objective", skillKey: "games.needs.skill", accent: "#47b7a0" },
  { id: "sorter", number: "03", icon: "coins", age: "7–10", duration: "2–4", titleKey: "games.sorter.title", shortKey: "games.sorter.short", objectiveKey: "games.sorter.objective", skillKey: "games.sorter.skill", accent: "#f5b64d" },
  { id: "budget", number: "04", icon: "wallet", age: "8–13", duration: "4–6", titleKey: "games.budget.title", shortKey: "games.budget.short", objectiveKey: "games.budget.objective", skillKey: "games.budget.skill", accent: "#4da2ff", image: "/manus-storage/profitspatrol-budget-scene_a244bb33.png" },
  { id: "savings", number: "05", icon: "piggy", age: "8–13", duration: "3–6", titleKey: "games.savings.title", shortKey: "games.savings.short", objectiveKey: "games.savings.objective", skillKey: "games.savings.skill", accent: "#47b7a0" },
  { id: "change", number: "06", icon: "receipt", age: "7–12", duration: "2–4", titleKey: "games.change.title", shortKey: "games.change.short", objectiveKey: "games.change.objective", skillKey: "games.change.skill", accent: "#ff8a51" },
  { id: "detective", number: "07", icon: "search", age: "8–13", duration: "3–5", titleKey: "games.detective.title", shortKey: "games.detective.short", objectiveKey: "games.detective.objective", skillKey: "games.detective.skill", accent: "#765ce8" },
  { id: "discount", number: "08", icon: "badge", age: "8–14", duration: "2–5", titleKey: "games.discount.title", shortKey: "games.discount.short", objectiveKey: "games.discount.objective", skillKey: "games.discount.skill", accent: "#fd5a7d" },
  { id: "cashflow", number: "09", icon: "store", age: "10–16", duration: "4–7", titleKey: "games.cashflow.title", shortKey: "games.cashflow.short", objectiveKey: "games.cashflow.objective", skillKey: "games.cashflow.skill", accent: "#2a9d8f", image: "/manus-storage/profitspatrol-cashflow-scene_86e90589.png" },
  { id: "maze", number: "10", icon: "route", age: "9–15", duration: "3–6", titleKey: "games.maze.title", shortKey: "games.maze.short", objectiveKey: "games.maze.objective", skillKey: "games.maze.skill", accent: "#356de1" },
  { id: "lemonade", number: "11", icon: "store", age: "7–11", duration: "4–7", titleKey: "games.lemonade.title", shortKey: "games.lemonade.short", objectiveKey: "games.lemonade.objective", skillKey: "games.lemonade.skill", accent: "#f2a93b", image: "/manus-storage/profitspatrol-lemonade-boss_fc5440d1.png" },
  { id: "snack", number: "12", icon: "store", age: "8–12", duration: "4–7", titleKey: "games.snack.title", shortKey: "games.snack.short", objectiveKey: "games.snack.objective", skillKey: "games.snack.skill", accent: "#e7774b", image: "/manus-storage/profitspatrol-snack-shack_45948480.png" },
  { id: "tshirt", number: "13", icon: "store", age: "9–14", duration: "5–8", titleKey: "games.tshirt.title", shortKey: "games.tshirt.short", objectiveKey: "games.tshirt.objective", skillKey: "games.tshirt.skill", accent: "#8c69d6", image: "/manus-storage/profitspatrol-tshirt-tycoon_780eac04.png" },
  { id: "pet", number: "14", icon: "store", age: "9–14", duration: "5–8", titleKey: "games.pet.title", shortKey: "games.pet.short", objectiveKey: "games.pet.objective", skillKey: "games.pet.skill", accent: "#4fab8a", image: "/manus-storage/profitspatrol-pet-shop-manager_8e2030bf.png" },
  { id: "cafe", number: "15", icon: "store", age: "10–15", duration: "6–10", titleKey: "games.cafe.title", shortKey: "games.cafe.short", objectiveKey: "games.cafe.objective", skillKey: "games.cafe.skill", accent: "#b85a43", image: "/manus-storage/profitspatrol-mini-cafe_01d5224d.png" },
  { id: "adagency", number: "16", icon: "badge", age: "9–14", duration: "5–8", titleKey: "games.adagency.title", shortKey: "games.adagency.short", objectiveKey: "games.adagency.objective", skillKey: "games.adagency.skill", accent: "#ff6b4a", image: "/manus-storage/profitspatrol-ad-agency_318db0cb.png" },
  { id: "customerquest", number: "17", icon: "search", age: "9–14", duration: "5–8", titleKey: "games.customerquest.title", shortKey: "games.customerquest.short", objectiveKey: "games.customerquest.objective", skillKey: "games.customerquest.skill", accent: "#47b7a0", image: "/manus-storage/profitspatrol-customer-quest_a18309cc.png" },
  { id: "salesmaster", number: "18", icon: "badge", age: "9–14", duration: "5–8", titleKey: "games.salesmaster.title", shortKey: "games.salesmaster.short", objectiveKey: "games.salesmaster.objective", skillKey: "games.salesmaster.skill", accent: "#f2a93b", image: "/manus-storage/profitspatrol-sales-master_bfa7c59c.png" },
  { id: "brandbuilder", number: "19", icon: "shapes", age: "9–14", duration: "5–8", titleKey: "games.brandbuilder.title", shortKey: "games.brandbuilder.short", objectiveKey: "games.brandbuilder.objective", skillKey: "games.brandbuilder.skill", accent: "#8c69d6", image: "/manus-storage/profitspatrol-brand-builder_1598968b.png" },
  { id: "marketingmix", number: "20", icon: "target", age: "10–15", duration: "5–9", titleKey: "games.marketingmix.title", shortKey: "games.marketingmix.short", objectiveKey: "games.marketingmix.objective", skillKey: "games.marketingmix.skill", accent: "#4da2ff", image: "/manus-storage/profitspatrol-marketing-mix_4ac7d08e.png" },
  { id: "investisland", number: "21", icon: "route", age: "11–17", duration: "5–8", titleKey: "games.investisland.title", shortKey: "games.investisland.short", objectiveKey: "games.investisland.objective", skillKey: "games.investisland.skill", accent: "#2a9d8f", image: "/manus-storage/profitspatrol-investment-island_49643be5.png" },
  { id: "riskradar", number: "22", icon: "target", age: "10–16", duration: "4–7", titleKey: "games.riskradar.title", shortKey: "games.riskradar.short", objectiveKey: "games.riskradar.objective", skillKey: "games.riskradar.skill", accent: "#356de1", image: "/manus-storage/profitspatrol-risk-radar_410cb874.png" },
  { id: "portfolioquest", number: "23", icon: "shapes", age: "12–17", duration: "6–10", titleKey: "games.portfolioquest.title", shortKey: "games.portfolioquest.short", objectiveKey: "games.portfolioquest.objective", skillKey: "games.portfolioquest.skill", accent: "#f2a93b", image: "/manus-storage/profitspatrol-portfolio-quest_42540385.png" },
  { id: "compoundmtn", number: "24", icon: "piggy", age: "10–17", duration: "4–7", titleKey: "games.compoundmtn.title", shortKey: "games.compoundmtn.short", objectiveKey: "games.compoundmtn.objective", skillKey: "games.compoundmtn.skill", accent: "#765ce8", image: "/manus-storage/profitspatrol-compound-mountain_505e0dfb.png" },
  { id: "scamdetective", number: "25", icon: "search", age: "10–17", duration: "5–8", titleKey: "games.scamdetective.title", shortKey: "games.scamdetective.short", objectiveKey: "games.scamdetective.objective", skillKey: "games.scamdetective.skill", accent: "#ff6b4a", image: "/manus-storage/profitspatrol-scam-detective_fe5d6817.png" },
  { id: "timetycoon", number: "26", icon: "target", age: "9–15", duration: "5–8", titleKey: "games.timetycoon.title", shortKey: "games.timetycoon.short", objectiveKey: "games.timetycoon.objective", skillKey: "games.timetycoon.skill", accent: "#ff6b4a", image: "/manus-storage/profitspatrol-time-tycoon_bc91e7a1.png" },
  { id: "teambuilder", number: "27", icon: "shapes", age: "10–16", duration: "5–8", titleKey: "games.teambuilder.title", shortKey: "games.teambuilder.short", objectiveKey: "games.teambuilder.objective", skillKey: "games.teambuilder.skill", accent: "#47b7a0", image: "/manus-storage/profitspatrol-team-builder_7b77cdec.png" },
  { id: "supplychain", number: "28", icon: "route", age: "10–16", duration: "5–9", titleKey: "games.supplychain.title", shortKey: "games.supplychain.short", objectiveKey: "games.supplychain.objective", skillKey: "games.supplychain.skill", accent: "#356de1", image: "/manus-storage/profitspatrol-supply-chain-rush_2db2c684.png" },
  { id: "inventorymaster", number: "29", icon: "store", age: "9–15", duration: "5–8", titleKey: "games.inventorymaster.title", shortKey: "games.inventorymaster.short", objectiveKey: "games.inventorymaster.objective", skillKey: "games.inventorymaster.skill", accent: "#47b7a0", image: "/manus-storage/profitspatrol-inventory-master_f4b22796.png" },
  { id: "businesscrisis", number: "30", icon: "target", age: "11–17", duration: "6–10", titleKey: "games.businesscrisis.title", shortKey: "games.businesscrisis.short", objectiveKey: "games.businesscrisis.objective", skillKey: "games.businesscrisis.skill", accent: "#ff6b4a", image: "/manus-storage/profitspatrol-business-crisis_7a8e6f83.png" },
  { id: "ideafactory", number: "31", icon: "shapes", age: "9–15", duration: "5–8", titleKey: "games.ideafactory.title", shortKey: "games.ideafactory.short", objectiveKey: "games.ideafactory.objective", skillKey: "games.ideafactory.skill", accent: "#f2a93b" },
  { id: "productlab", number: "32", icon: "store", age: "10–16", duration: "5–8", titleKey: "games.productlab.title", shortKey: "games.productlab.short", objectiveKey: "games.productlab.objective", skillKey: "games.productlab.skill", accent: "#47b7a0" },
  { id: "prototyperush", number: "33", icon: "target", age: "10–16", duration: "5–9", titleKey: "games.prototyperush.title", shortKey: "games.prototyperush.short", objectiveKey: "games.prototyperush.objective", skillKey: "games.prototyperush.skill", accent: "#356de1" },
  { id: "customerfeedback", number: "34", icon: "search", age: "9–15", duration: "5–8", titleKey: "games.customerfeedback.title", shortKey: "games.customerfeedback.short", objectiveKey: "games.customerfeedback.objective", skillKey: "games.customerfeedback.skill", accent: "#ff6b4a" },
  { id: "innovationchallenge", number: "35", icon: "route", age: "11–17", duration: "6–10", titleKey: "games.innovationchallenge.title", shortKey: "games.innovationchallenge.short", objectiveKey: "games.innovationchallenge.objective", skillKey: "games.innovationchallenge.skill", accent: "#765ce8" },
  { id: "negotiationarena", number: "36", icon: "target", age: "10–16", duration: "6–9", titleKey: "games.negotiationarena.title", shortKey: "games.negotiationarena.short", objectiveKey: "games.negotiationarena.objective", skillKey: "games.negotiationarena.skill", accent: "#f2a93b" },
  { id: "teamcaptain", number: "37", icon: "shapes", age: "10–16", duration: "6–9", titleKey: "games.teamcaptain.title", shortKey: "games.teamcaptain.short", objectiveKey: "games.teamcaptain.objective", skillKey: "games.teamcaptain.skill", accent: "#47b7a0" },
  { id: "dealmaker", number: "38", icon: "wallet", age: "11–17", duration: "6–10", titleKey: "games.dealmaker.title", shortKey: "games.dealmaker.short", objectiveKey: "games.dealmaker.objective", skillKey: "games.dealmaker.skill", accent: "#356de1" },
  { id: "communicationlab", number: "39", icon: "search", age: "9–15", duration: "5–8", titleKey: "games.communicationlab.title", shortKey: "games.communicationlab.short", objectiveKey: "games.communicationlab.objective", skillKey: "games.communicationlab.skill", accent: "#ff6b4a" },
  { id: "leadershipquest", number: "40", icon: "route", age: "11–17", duration: "6–10", titleKey: "games.leadershipquest.title", shortKey: "games.leadershipquest.short", objectiveKey: "games.leadershipquest.objective", skillKey: "games.leadershipquest.skill", accent: "#765ce8" },
  { id: "marketwars", number: "41", icon: "target", age: "11–17", duration: "6–10", titleKey: "games.marketwars.title", shortKey: "games.marketwars.short", objectiveKey: "games.marketwars.objective", skillKey: "games.marketwars.skill", accent: "#f2a93b" },
  { id: "strategyempire", number: "42", icon: "route", age: "11–17", duration: "7–11", titleKey: "games.strategyempire.title", shortKey: "games.strategyempire.short", objectiveKey: "games.strategyempire.objective", skillKey: "games.strategyempire.skill", accent: "#765ce8" },
  { id: "competitorhunt", number: "43", icon: "search", age: "10–16", duration: "6–10", titleKey: "games.competitorhunt.title", shortKey: "games.competitorhunt.short", objectiveKey: "games.competitorhunt.objective", skillKey: "games.competitorhunt.skill", accent: "#4da2ff" },
  { id: "growthengine", number: "44", icon: "target", age: "11–17", duration: "6–10", titleKey: "games.growthengine.title", shortKey: "games.growthengine.short", objectiveKey: "games.growthengine.objective", skillKey: "games.growthengine.skill", accent: "#47b7a0" },
  { id: "businesstycoon", number: "45", icon: "store", age: "12–17", duration: "8–12", titleKey: "games.businesstycoon.title", shortKey: "games.businesstycoon.short", objectiveKey: "games.businesstycoon.objective", skillKey: "games.businesstycoon.skill", accent: "#f2a93b" },
  { id: "salesmasterten", number: "46", icon: "badge", age: "10–16", duration: "6–9", titleKey: "games.salesmasterten.title", shortKey: "games.salesmasterten.short", objectiveKey: "games.salesmasterten.objective", skillKey: "games.salesmasterten.skill", accent: "#4da2ff" },
  { id: "marketingmachine", number: "47", icon: "target", age: "10–16", duration: "6–10", titleKey: "games.marketingmachine.title", shortKey: "games.marketingmachine.short", objectiveKey: "games.marketingmachine.objective", skillKey: "games.marketingmachine.skill", accent: "#ff6b4a" },
  { id: "ecommercerush", number: "48", icon: "store", age: "10–16", duration: "7–10", titleKey: "games.ecommercerush.title", shortKey: "games.ecommercerush.short", objectiveKey: "games.ecommercerush.objective", skillKey: "games.ecommercerush.skill", accent: "#47b7a0" },
  { id: "pitchbattle", number: "49", icon: "target", age: "11–17", duration: "7–10", titleKey: "games.pitchbattle.title", shortKey: "games.pitchbattle.short", objectiveKey: "games.pitchbattle.objective", skillKey: "games.pitchbattle.skill", accent: "#765ce8" },
  { id: "startuplaunch", number: "50", icon: "badge", age: "11–17", duration: "10–14", titleKey: "games.startuplaunch.title", shortKey: "games.startuplaunch.short", objectiveKey: "games.startuplaunch.objective", skillKey: "games.startuplaunch.skill", accent: "#f5b64d" },
];

export const getGame = (id: GameId) => GAME_REGISTRY.find((game) => game.id === id)!;
