/**
 * ProfitsPatrol design reminder: Batch 04 teaches thoughtful marketing and sales
 * through friendly, ethical choices inside the established business neighborhood.
 */
import { BadgeCheck, Handshake, Palette, Rocket, Sparkles, Store, Target, Trophy, Users } from "lucide-react";
import { useState } from "react";
import { useTranslation } from "react-i18next";
import type { GameResult } from "./GameRunner";

type SharedProps = { paused: boolean; onEnd: (result: GameResult) => void };
type SalesScenario = { customer: string; need: string; objection: string; responses: string[]; correctResponse: number; offers: string[]; correctOffer: number };

function Choice({ title, value, options, onPick, disabled, label }: { title: string; value: string; options: string[]; onPick: (value: string) => void; disabled: boolean; label: (key: string) => string }) {
  return <section className="venture-choice"><p>{title}</p><div>{options.map((option) => <button type="button" key={option} disabled={disabled} onClick={() => onPick(option)} className={value === option ? "venture-choice__active" : ""}>{label(option)}</button>)}</div></section>;
}

function Metric({ label, value, positive }: { label: string; value: string; positive?: boolean }) {
  return <div className={`venture-metric ${positive ? "venture-metric--mint" : ""}`}><span>{label}</span><b>{value}</b></div>;
}

export function SalesMaster({ paused, onEnd }: SharedProps) {
  const { t } = useTranslation();
  const scenarios = t("games.salesmaster.scenarios", { returnObjects: true }) as unknown as SalesScenario[];
  const [round, setRound] = useState(0); const [response, setResponse] = useState<number | null>(null); const [offer, setOffer] = useState<number | null>(null); const [trust, setTrust] = useState(45); const [score, setScore] = useState(0);
  const scenario = scenarios[round]; const responseFit = response === scenario.correctResponse; const offerFit = offer === scenario.correctOffer;
  const finishRound = (index: number) => { if (paused || offer !== null) return; const gain = (responseFit ? 17 : 3) + (index === scenario.correctOffer ? 20 : 4); setOffer(index); setScore((value) => value + gain); setTrust((value) => Math.min(100, value + gain)); };
  const next = () => { if (round === scenarios.length - 1) { onEnd({ achieved: score >= 70, score, stars: score >= 90 ? 3 : score >= 70 ? 2 : 1, message: t("games.salesmaster.result", { score, trust }) }); return; } setRound((value) => value + 1); setResponse(null); setOffer(null); };
  return <div className="game-stage venture-stage"><div className="game-play-header"><span className="game-play-header__icon"><Handshake size={20}/></span><div><p className="stage-kicker">{t("games.salesmaster.objective")}</p><div className="stage-scoreline"><b>{t("games.salesmaster.trust")}: {trust}%</b><span>{round + 1}/{scenarios.length}</span></div></div></div><div className="venture-board"><div className="venture-banner"><img src="/manus-storage/profitspatrol-sales-master_bfa7c59c.png" alt=""/><div><span>{t("games.salesmaster.customer")}</span><b>🤝 {scenario.customer}</b></div></div><div className="customer-quest__brief"><p className="stage-kicker">{t("games.salesmaster.need")}</p><h2>{scenario.need}</h2><div className="customer-quest__product"><Handshake size={18}/><span>{scenario.objection}</span></div></div>{response === null ? <section className="venture-choice"><p>{t("games.salesmaster.respond")}</p><div>{scenario.responses.map((item, index) => <button type="button" key={item} disabled={paused} onClick={() => setResponse(index)}>{item}</button>)}</div></section> : offer === null ? <section className="venture-choice"><p>{t("games.salesmaster.offer")}</p><div>{scenario.offers.map((item, index) => <button type="button" key={item} disabled={paused} onClick={() => finishRound(index)}>{item}</button>)}</div></section> : <div className="venture-results"><div className="venture-metrics"><Metric label={t("games.salesmaster.honesty")} value={responseFit ? "✓" : "↻"} positive={responseFit}/><Metric label={t("games.salesmaster.match")} value={offerFit ? "✓" : "↻"} positive={offerFit}/><Metric label={t("games.salesmaster.trust")} value={`${trust}%`} positive={trust >= 70}/></div><p className="venture-insight">{responseFit && offerFit ? t("games.salesmaster.helpful") : t("games.salesmaster.improve")}</p><button type="button" disabled={paused} onClick={next} className="primary-action">{round === scenarios.length - 1 ? t("games.salesmaster.finish") : t("games.salesmaster.nextCustomer")} <Trophy size={17}/></button></div>}</div></div>;
}

export function BrandBuilder({ paused, onEnd }: SharedProps) {
  const { t } = useTranslation();
  const [product, setProduct] = useState("books"); const [audience, setAudience] = useState("readers"); const [personality, setPersonality] = useState("curious"); const [visual, setVisual] = useState("clear"); const [stage, setStage] = useState<"build" | "consistency" | "results">("build"); const [consistency, setConsistency] = useState(0);
  const productFit = (product === "books" && audience === "readers") || (product === "bikes" && audience === "commuters") || (product === "cocoa" && audience === "families");
  const personalityFit = (product === "books" && personality === "curious") || (product === "bikes" && personality === "bold") || (product === "cocoa" && personality === "friendly");
  const visualFit = (product === "books" && visual === "clear") || (product === "bikes" && visual === "dynamic") || (product === "cocoa" && visual === "warm");
  const base = (productFit ? 34 : 10) + (personalityFit ? 28 : 8) + (visualFit ? 23 : 7); const total = base + consistency * 8;
  const finish = () => onEnd({ achieved: total >= 70, score: total, stars: total >= 90 ? 3 : total >= 70 ? 2 : 1, message: t("games.brandbuilder.result", { score: total, promise: t(`games.brandbuilder.${product}`) }) });
  return <div className="game-stage venture-stage"><div className="game-play-header"><span className="game-play-header__icon"><Palette size={20}/></span><div><p className="stage-kicker">{t("games.brandbuilder.objective")}</p><div className="stage-scoreline"><b>{t("games.brandbuilder.fit")}: {stage === "results" ? `${total}%` : "—"}</b><span>{t("games.brandbuilder.promise")}</span></div></div></div><div className="venture-board"><div className="venture-banner"><img src="/manus-storage/profitspatrol-brand-builder_1598968b.png" alt=""/><div><span>{t("games.brandbuilder.title")}</span><b>🎨 {t("games.brandbuilder.promise")}</b></div></div>{stage === "build" ? <><div className="venture-grid"><Choice title={t("games.brandbuilder.product")} value={product} options={["books", "bikes", "cocoa"]} onPick={setProduct} disabled={paused} label={(key) => t(`games.brandbuilder.${key}`)}/><Choice title={t("games.brandbuilder.audience")} value={audience} options={["readers", "commuters", "families"]} onPick={setAudience} disabled={paused} label={(key) => t(`games.brandbuilder.${key}`)}/><Choice title={t("games.brandbuilder.personality")} value={personality} options={["curious", "bold", "friendly"]} onPick={setPersonality} disabled={paused} label={(key) => t(`games.brandbuilder.${key}`)}/><Choice title={t("games.brandbuilder.visual")} value={visual} options={["clear", "dynamic", "warm"]} onPick={setVisual} disabled={paused} label={(key) => t(`games.brandbuilder.${key}`)}/></div><button type="button" disabled={paused} onClick={() => setStage("consistency")} className="primary-action mt-6">{t("games.brandbuilder.test")} <BadgeCheck size={17}/></button></> : stage === "consistency" ? <div className="venture-results"><p className="stage-kicker">{t("games.brandbuilder.consistency")}</p><h2>{t("games.brandbuilder.challenge")}</h2><section className="venture-choice"><div><button type="button" disabled={paused} onClick={() => { setConsistency(2); setStage("results"); }}>{t("games.brandbuilder.keep")}</button><button type="button" disabled={paused} onClick={() => { setConsistency(0); setStage("results"); }}>{t("games.brandbuilder.drift")}</button></div></section></div> : <div className="venture-results"><div className="venture-metrics"><Metric label={t("games.brandbuilder.audienceFit")} value={productFit ? "✓" : "↻"} positive={productFit}/><Metric label={t("games.brandbuilder.identity")} value={personalityFit && visualFit ? "✓" : "↻"} positive={personalityFit && visualFit}/><Metric label={t("games.brandbuilder.consistency")} value={`${consistency}/2`} positive={consistency === 2}/><Metric label={t("games.brandbuilder.fit")} value={`${total}%`} positive={total >= 70}/></div><p className="venture-insight">{total >= 70 ? t("games.brandbuilder.strong") : t("games.brandbuilder.adjust")}</p><button type="button" disabled={paused} onClick={finish} className="primary-action">{t("games.brandbuilder.review")} <Trophy size={17}/></button></div>}</div></div>;
}

export function MarketingMix({ paused, onEnd }: SharedProps) {
  const { t } = useTranslation();
  const [product, setProduct] = useState("durable"); const [price, setPrice] = useState("fair"); const [place, setPlace] = useState("local"); const [promotion, setPromotion] = useState("demo"); const [stage, setStage] = useState<"build" | "results">("build");
  const productFit = product === "durable"; const priceFit = price === "fair"; const placeFit = place === "local"; const promotionFit = promotion === "demo"; const score = (productFit ? 26 : 8) + (priceFit ? 25 : 8) + (placeFit ? 24 : 8) + (promotionFit ? 25 : 8); const interest = 80 + (promotionFit ? 80 : 20) + (placeFit ? 30 : 0); const sales = Math.round(interest * (priceFit ? .42 : .2)); const satisfaction = Math.round(((productFit ? 35 : 12) + (priceFit ? 30 : 12) + (placeFit ? 20 : 8) + (promotionFit ? 15 : 7)));
  const finish = () => onEnd({ achieved: score >= 70, score, stars: score >= 90 ? 3 : score >= 70 ? 2 : 1, message: t("games.marketingmix.result", { sales, satisfaction, score }) });
  return <div className="game-stage venture-stage"><div className="game-play-header"><span className="game-play-header__icon"><Store size={20}/></span><div><p className="stage-kicker">{t("games.marketingmix.objective")}</p><div className="stage-scoreline"><b>{t("games.marketingmix.fit")}: {stage === "results" ? `${score}%` : "—"}</b><span>{t("games.marketingmix.launchLabel")}</span></div></div></div><div className="venture-board"><div className="venture-banner"><img src="/manus-storage/profitspatrol-marketing-mix_4ac7d08e.png" alt=""/><div><span>{t("games.marketingmix.title")}</span><b>🧩 {t("games.marketingmix.fourPs")}</b></div></div>{stage === "build" ? <><div className="venture-grid"><Choice title={t("games.marketingmix.product")} value={product} options={["durable", "flashy", "basic"]} onPick={setProduct} disabled={paused} label={(key) => t(`games.marketingmix.${key}`)}/><Choice title={t("games.marketingmix.price")} value={price} options={["fair", "high", "low"]} onPick={setPrice} disabled={paused} label={(key) => t(`games.marketingmix.${key}`)}/><Choice title={t("games.marketingmix.place")} value={place} options={["local", "hidden", "far"]} onPick={setPlace} disabled={paused} label={(key) => t(`games.marketingmix.${key}`)}/><Choice title={t("games.marketingmix.promotion")} value={promotion} options={["demo", "hype", "coupon"]} onPick={setPromotion} disabled={paused} label={(key) => t(`games.marketingmix.${key}`)}/></div><button type="button" disabled={paused} onClick={() => setStage("results")} className="primary-action mt-6">{t("games.marketingmix.launch")} <Rocket size={17}/></button></> : <div className="venture-results"><div className="venture-metrics"><Metric label={t("games.marketingmix.sales")} value={`${sales}`} positive={sales >= 65}/><Metric label={t("games.marketingmix.satisfaction")} value={`${satisfaction}%`} positive={satisfaction >= 70}/><Metric label={t("games.marketingmix.score")} value={`${score}/100`} positive={score >= 70}/><Metric label={t("games.marketingmix.fit")} value={`${score}%`} positive={score >= 70}/></div><p className="venture-insight">{score >= 70 ? t("games.marketingmix.strong") : t("games.marketingmix.adjust")}</p><div className="flex flex-wrap justify-center gap-3"><button type="button" disabled={paused} onClick={() => setStage("build")} className="secondary-action">{t("games.marketingmix.improve")} <Sparkles size={17}/></button><button type="button" disabled={paused} onClick={finish} className="primary-action">{t("games.marketingmix.review")} <Trophy size={17}/></button></div></div>}</div></div>;
}
