/* Launch City design contract: tactile, ethical business role-play; warm cream surfaces, coral learning cues, and child-friendly decisions over dashboards. */
import { BadgeCheck, BarChart3, Box, Flag, Handshake, Lightbulb, Megaphone, MessageCircleHeart, Rocket, SearchCheck, ShoppingBag, Sparkles, UserRoundCheck, UsersRound } from "lucide-react";
import { useState } from "react";
import { useTranslation } from "react-i18next";
import type { GameResult } from "./GameRunner";

type SharedProps = { paused: boolean; onEnd: (result: GameResult) => void };
type Discovery = "use" | "budget" | "preference";
type Offer = "planner" | "flashbox" | "ribbon";
type Response = "honest" | "pressure" | "ignore";

const scoreStars = (score: number) => score >= 90 ? 3 : score >= 65 ? 2 : 1;
const Metric = ({ label, value, positive }: { label: string; value: number | string; positive?: boolean }) => <div className={`venture-metric ${positive ? "venture-metric--mint" : ""}`}><span>{label}</span><b>{value}</b></div>;

export function SalesMasterTen({ paused, onEnd }: SharedProps) {
  const { t } = useTranslation();
  const [stage, setStage] = useState<"discover" | "recommend" | "respond" | "review">("discover");
  const [discovered, setDiscovered] = useState<Discovery[]>([]);
  const [offer, setOffer] = useState<Offer | null>(null);
  const [response, setResponse] = useState<Response | null>(null);
  const discoveryScore = discovered.length * 12;
  const match = offer === "planner" ? 96 : offer === "flashbox" ? 49 : 25;
  const clarity = offer === "planner" ? 91 : offer === "flashbox" ? 63 : 42;
  const trust = Math.min(100, 38 + discoveryScore + (response === "honest" ? 26 : response === "pressure" ? -6 : 7) + (offer === "planner" ? 12 : 0));
  const satisfaction = Math.round((match + clarity + trust) / 3);
  const toggleDiscovery = (id: Discovery) => { if (!paused) setDiscovered((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id]); };
  const finish = () => onEnd({ achieved: satisfaction >= 62, score: satisfaction, stars: scoreStars(satisfaction), message: t("games.salesmasterten.result", { trust, match, satisfaction }) });

  return <div className="game-stage venture-stage batch10-stage">
    <header className="game-play-header"><span className="game-play-header__icon"><Handshake size={20}/></span><div><p className="stage-kicker">{t("games.salesmasterten.objective")}</p><div className="stage-scoreline"><b>{t("games.salesmasterten.skill")}</b><span>{t("games.salesmasterten.customer")}</span></div></div></header>
    <div className="venture-board">
      <div className="batch10-banner batch10-banner--sales"><UserRoundCheck/><div><span>{t("games.salesmasterten.title")}</span><b>{t("games.salesmasterten.customer")}</b></div></div>
      {stage === "discover" && <div className="batch10-flow"><div className="batch10-customer-note"><SearchCheck size={18}/><p>{t("games.salesmasterten.customerBrief")}</p></div><section><p>{t("games.salesmasterten.discover")}</p><div className="batch10-choice-grid">{(["use", "budget", "preference"] as Discovery[]).map((id) => <button key={id} type="button" disabled={paused} onClick={() => toggleDiscovery(id)} className={discovered.includes(id) ? "batch10-choice batch10-choice--active" : "batch10-choice"}><b>{t(`games.salesmasterten.questions.${id}.title`)}</b><span>{t(`games.salesmasterten.questions.${id}.note`)}</span></button>)}</div></section><div className="venture-metrics"><Metric label={t("games.salesmasterten.listening")} value={`${discovered.length}/3`} positive={discovered.length >= 2}/><Metric label={t("games.salesmasterten.trust")} value={38 + discoveryScore} positive={discovered.length >= 2}/></div><button type="button" className="primary-action" disabled={paused || discovered.length < 2} onClick={() => setStage("recommend")}>{t("games.salesmasterten.recommend")} <Sparkles size={17}/></button></div>}
      {stage === "recommend" && <div className="batch10-flow"><div className="batch10-customer-note"><MessageCircleHeart size={18}/><p>{t("games.salesmasterten.need")}</p></div><section><p>{t("games.salesmasterten.offer")}</p><div className="batch10-choice-grid">{(["planner", "flashbox", "ribbon"] as Offer[]).map((id) => <button key={id} type="button" disabled={paused} onClick={() => setOffer(id)} className={offer === id ? "batch10-choice batch10-choice--active" : "batch10-choice"}><b>{t(`games.salesmasterten.offers.${id}.title`)}</b><span>{t(`games.salesmasterten.offers.${id}.note`)}</span></button>)}</div></section><div className="venture-metrics"><Metric label={t("games.salesmasterten.match")} value={offer ? match : "—"} positive={match >= 75}/><Metric label={t("games.salesmasterten.clarity")} value={offer ? clarity : "—"} positive={clarity >= 75}/></div><button type="button" className="primary-action" disabled={paused || !offer} onClick={() => setStage("respond")}>{t("games.salesmasterten.explainValue")} <BadgeCheck size={17}/></button></div>}
      {stage === "respond" && <div className="batch10-flow"><div className="batch10-customer-note"><MessageCircleHeart size={18}/><p>{t("games.salesmasterten.objection")}</p></div><section><p>{t("games.salesmasterten.respond")}</p><div className="batch10-choice-grid">{(["honest", "pressure", "ignore"] as Response[]).map((id) => <button key={id} type="button" disabled={paused} onClick={() => setResponse(id)} className={response === id ? "batch10-choice batch10-choice--active" : "batch10-choice"}><b>{t(`games.salesmasterten.responses.${id}.title`)}</b><span>{t(`games.salesmasterten.responses.${id}.note`)}</span></button>)}</div></section><div className="venture-metrics"><Metric label={t("games.salesmasterten.trust")} value={response ? trust : "—"} positive={trust >= 70}/><Metric label={t("games.salesmasterten.match")} value={match} positive={match >= 75}/></div><button type="button" className="primary-action" disabled={paused || !response} onClick={() => setStage("review")}>{t("games.salesmasterten.review")} <Handshake size={17}/></button></div>}
      {stage === "review" && <div className="venture-results"><p className="stage-kicker">{t(satisfaction >= 76 ? "games.salesmasterten.outcome.accept" : satisfaction >= 60 ? "games.salesmasterten.outcome.consider" : "games.salesmasterten.outcome.revisit")}</p><div className="venture-metrics"><Metric label={t("games.salesmasterten.trust")} value={trust} positive={trust >= 70}/><Metric label={t("games.salesmasterten.match")} value={match} positive={match >= 75}/><Metric label={t("games.salesmasterten.satisfaction")} value={satisfaction} positive={satisfaction >= 65}/></div><p className="venture-insight">{t(satisfaction >= 72 ? "games.salesmasterten.strong" : "games.salesmasterten.improve")}</p><button type="button" disabled={paused} onClick={finish} className="primary-action">{t("games.salesmasterten.finish")} <BadgeCheck size={17}/></button></div>}
    </div>
  </div>;
}

type CampaignChoice = "students" | "everyone" | "unknown" | "prepare" | "hype" | "discount" | "community" | "feed" | "poster" | "balanced" | "tiny" | "allin";
type TestChoice = "clear" | "loud";
type OptimizeChoice = "learn" | "overspend" | "ignore";

export function MarketingMachine({ paused, onEnd }: SharedProps) {
  const { t } = useTranslation();
  const [stage, setStage] = useState<"build" | "test" | "optimize" | "review">("build");
  const [choices, setChoices] = useState<Record<string, CampaignChoice | null>>({ audience: null, message: null, channel: null, budget: null });
  const [test, setTest] = useState<TestChoice | null>(null);
  const [optimize, setOptimize] = useState<OptimizeChoice | null>(null);
  const ready = Object.values(choices).every(Boolean);
  const base = (choices.audience === "students" ? 24 : 4) + (choices.message === "prepare" ? 24 : 7) + (choices.channel === "community" ? 20 : 10) + (choices.budget === "balanced" ? 16 : 7);
  const campaignScore = Math.min(100, base + (test === "clear" ? 10 : 3) + (optimize === "learn" ? 12 : optimize === "ignore" ? 3 : 0));
  const reach = Math.round(38 + base * .65); const interest = Math.round(18 + base * .55); const feedback = test === "clear" ? 87 : test ? 46 : 0;
  const finish = () => onEnd({ achieved: campaignScore >= 62, score: campaignScore, stars: scoreStars(campaignScore), message: t("games.marketingmachine.result", { reach, interest, campaignScore }) });
  const choose = (key: string, value: CampaignChoice) => !paused && setChoices((current) => ({ ...current, [key]: value }));
  const campaignGroups: { key: string; values: CampaignChoice[] }[] = [{ key: "audience", values: ["students", "everyone", "unknown"] }, { key: "message", values: ["prepare", "hype", "discount"] }, { key: "channel", values: ["community", "feed", "poster"] }, { key: "budget", values: ["balanced", "tiny", "allin"] }];

  return <div className="game-stage venture-stage batch10-stage"><header className="game-play-header"><span className="game-play-header__icon"><Megaphone size={20}/></span><div><p className="stage-kicker">{t("games.marketingmachine.objective")}</p><div className="stage-scoreline"><b>{t("games.marketingmachine.skill")}</b><span>{t("games.marketingmachine.launch")}</span></div></div></header><div className="venture-board"><div className="batch10-banner batch10-banner--marketing"><BarChart3/><div><span>{t("games.marketingmachine.title")}</span><b>{t("games.marketingmachine.launch")}</b></div></div>
    {stage === "build" && <div className="batch10-flow"><div className="batch10-customer-note"><Megaphone size={18}/><p>{t("games.marketingmachine.brief")}</p></div><div className="batch10-campaign-grid">{campaignGroups.map((group) => <section key={group.key}><p>{t(`games.marketingmachine.groups.${group.key}`)}</p><div className="batch10-mini-options">{group.values.map((value) => <button type="button" key={value} disabled={paused} onClick={() => choose(group.key, value)} className={choices[group.key] === value ? "batch10-mini-option batch10-mini-option--active" : "batch10-mini-option"}><b>{t(`games.marketingmachine.choices.${value}.title`)}</b><span>{t(`games.marketingmachine.choices.${value}.note`)}</span></button>)}</div></section>)}</div><div className="venture-metrics"><Metric label={t("games.marketingmachine.fit")} value={ready ? base : "—"} positive={base >= 65}/><Metric label={t("games.marketingmachine.readiness")} value={`${Object.values(choices).filter(Boolean).length}/4`} positive={ready}/></div><button type="button" className="primary-action" disabled={paused || !ready} onClick={() => setStage("test")}>{t("games.marketingmachine.launch")} <Megaphone size={17}/></button></div>}
    {stage === "test" && <div className="batch10-flow"><div className="batch10-customer-note"><BarChart3 size={18}/><p>{t("games.marketingmachine.metricsBrief", { reach, interest })}</p></div><section><p>{t("games.marketingmachine.test")}</p><div className="batch10-choice-grid">{(["clear", "loud"] as TestChoice[]).map((id) => <button type="button" key={id} disabled={paused} onClick={() => setTest(id)} className={test === id ? "batch10-choice batch10-choice--active" : "batch10-choice"}><b>{t(`games.marketingmachine.tests.${id}.title`)}</b><span>{t(`games.marketingmachine.tests.${id}.note`)}</span></button>)}</div></section><div className="venture-metrics"><Metric label={t("games.marketingmachine.reach")} value={reach} positive={reach >= 70}/><Metric label={t("games.marketingmachine.interest")} value={interest} positive={interest >= 55}/><Metric label={t("games.marketingmachine.feedback")} value={test ? feedback : "—"} positive={feedback >= 65}/></div><button type="button" className="primary-action" disabled={paused || !test} onClick={() => setStage("optimize")}>{t("games.marketingmachine.optimize")} <Sparkles size={17}/></button></div>}
    {stage === "optimize" && <div className="batch10-flow"><div className="batch10-customer-note"><MessageCircleHeart size={18}/><p>{t("games.marketingmachine.feedbackBrief")}</p></div><section><p>{t("games.marketingmachine.adjust")}</p><div className="batch10-choice-grid">{(["learn", "overspend", "ignore"] as OptimizeChoice[]).map((id) => <button type="button" key={id} disabled={paused} onClick={() => setOptimize(id)} className={optimize === id ? "batch10-choice batch10-choice--active" : "batch10-choice"}><b>{t(`games.marketingmachine.optimizations.${id}.title`)}</b><span>{t(`games.marketingmachine.optimizations.${id}.note`)}</span></button>)}</div></section><button type="button" className="primary-action" disabled={paused || !optimize} onClick={() => setStage("review")}>{t("games.marketingmachine.review")} <BadgeCheck size={17}/></button></div>}
    {stage === "review" && <div className="venture-results"><p className="stage-kicker">{t(campaignScore >= 75 ? "games.marketingmachine.outcome.strong" : "games.marketingmachine.outcome.growing")}</p><div className="venture-metrics"><Metric label={t("games.marketingmachine.fit")} value={base} positive={base >= 65}/><Metric label={t("games.marketingmachine.feedback")} value={feedback} positive={feedback >= 65}/><Metric label={t("games.marketingmachine.campaignScore")} value={campaignScore} positive={campaignScore >= 65}/></div><p className="venture-insight">{t(campaignScore >= 72 ? "games.marketingmachine.strong" : "games.marketingmachine.improve")}</p><button type="button" className="primary-action" disabled={paused} onClick={finish}>{t("games.marketingmachine.finish")} <BadgeCheck size={17}/></button></div>}
  </div></div>;
}

type StoreChoice = "kit" | "mystery" | "luxury";
type PriceChoice = "fair" | "low" | "high";
type StockChoice = "six" | "twelve" | "twenty";
type FulfilChoice = "careful" | "rushed" | "delayed";

export function ECommerceRush({ paused, onEnd }: SharedProps) {
  const { t } = useTranslation();
  const [stage, setStage] = useState<"setup" | "fulfil" | "review">("setup");
  const [store, setStore] = useState<StoreChoice | null>(null); const [price, setPrice] = useState<PriceChoice | null>(null); const [stock, setStock] = useState<StockChoice | null>(null); const [fulfil, setFulfil] = useState<FulfilChoice | null>(null);
  const stockCount = stock === "six" ? 6 : stock === "twelve" ? 12 : stock === "twenty" ? 20 : 0;
  const unitPrice = price === "low" ? 4 : price === "fair" ? 7 : price === "high" ? 11 : 0;
  const demand = Math.max(2, (store === "kit" ? 11 : store === "mystery" ? 7 : 5) + (price === "fair" ? 2 : price === "low" ? 1 : -2));
  const orders = Math.min(stockCount, demand); const stockout = Math.max(0, demand - stockCount); const leftover = Math.max(0, stockCount - orders);
  const revenue = orders * unitPrice; const fulfilCost = fulfil === "careful" ? orders : fulfil === "rushed" ? Math.ceil(orders * 1.7) : Math.ceil(orders * 1.25); const operatingCost = stockCount * 3 + fulfilCost + (leftover > 6 ? 6 : 0); const profit = revenue - operatingCost;
  const service = fulfil === "careful" ? 92 : fulfil === "rushed" ? 58 : 44;
  const storeFit = store === "kit" ? 92 : store === "mystery" ? 56 : 39;
  const score = Math.max(20, Math.min(100, Math.round((storeFit + service + (price === "fair" ? 86 : price === "low" ? 55 : 46) + (stock === "twelve" ? 84 : 52)) / 4)));
  const finish = () => onEnd({ achieved: score >= 62, score, stars: scoreStars(score), message: t("games.ecommercerush.result", { orders, revenue, profit, score }) });
  const options = <T extends string>(values: T[], selected: T | null, set: (value: T) => void, namespace: string) => <div className="batch10-mini-options">{values.map((value) => <button type="button" key={value} disabled={paused} onClick={() => set(value)} className={selected === value ? "batch10-mini-option batch10-mini-option--active" : "batch10-mini-option"}><b>{t(`${namespace}.${value}.title`)}</b><span>{t(`${namespace}.${value}.note`)}</span></button>)}</div>;
  return <div className="game-stage venture-stage batch10-stage"><header className="game-play-header"><span className="game-play-header__icon"><ShoppingBag size={20}/></span><div><p className="stage-kicker">{t("games.ecommercerush.objective")}</p><div className="stage-scoreline"><b>{t("games.ecommercerush.skill")}</b><span>{t("games.ecommercerush.storefront")}</span></div></div></header><div className="venture-board"><div className="batch10-banner batch10-banner--commerce"><Box/><div><span>{t("games.ecommercerush.title")}</span><b>{t("games.ecommercerush.storefront")}</b></div></div>
    {stage === "setup" && <div className="batch10-flow"><div className="batch10-customer-note"><ShoppingBag size={18}/><p>{t("games.ecommercerush.brief")}</p></div><div className="batch10-campaign-grid"><section><p>{t("games.ecommercerush.product")}</p>{options(["kit", "mystery", "luxury"], store, setStore, "games.ecommercerush.products")}</section><section><p>{t("games.ecommercerush.price")}</p>{options(["fair", "low", "high"], price, setPrice, "games.ecommercerush.prices")}</section><section><p>{t("games.ecommercerush.inventory")}</p>{options(["six", "twelve", "twenty"], stock, setStock, "games.ecommercerush.stocks")}</section></div><div className="venture-metrics"><Metric label={t("games.ecommercerush.storeFit")} value={store ? storeFit : "—"} positive={storeFit >= 70}/><Metric label={t("games.ecommercerush.stock")} value={stockCount || "—"} positive={stock === "twelve"}/></div><button type="button" className="primary-action" disabled={paused || !store || !price || !stock} onClick={() => setStage("fulfil")}>{t("games.ecommercerush.openStore")} <ShoppingBag size={17}/></button></div>}
    {stage === "fulfil" && <div className="batch10-flow"><div className="batch10-customer-note"><Box size={18}/><p>{t("games.ecommercerush.orderEvent", { demand, orders, stockout })}</p></div><section><p>{t("games.ecommercerush.fulfilment")}</p>{options(["careful", "rushed", "delayed"], fulfil, setFulfil, "games.ecommercerush.fulfilments")}</section><div className="venture-metrics"><Metric label={t("games.ecommercerush.orders")} value={orders} positive={orders >= 8}/><Metric label={t("games.ecommercerush.revenue")} value={revenue} positive={revenue >= 45}/><Metric label={t("games.ecommercerush.costs")} value={fulfil ? operatingCost : "—"} positive={operatingCost <= revenue}/></div><button type="button" className="primary-action" disabled={paused || !fulfil} onClick={() => setStage("review")}>{t("games.ecommercerush.review")} <BadgeCheck size={17}/></button></div>}
    {stage === "review" && <div className="venture-results"><p className="stage-kicker">{t(score >= 74 ? "games.ecommercerush.outcome.strong" : "games.ecommercerush.outcome.revise")}</p><div className="venture-metrics"><Metric label={t("games.ecommercerush.orders")} value={orders} positive={orders >= 8}/><Metric label={t("games.ecommercerush.revenue")} value={revenue} positive={revenue >= 45}/><Metric label={t("games.ecommercerush.profit")} value={profit} positive={profit >= 0}/><Metric label={t("games.ecommercerush.service")} value={service} positive={service >= 70}/></div><p className="venture-insight">{t(profit >= 0 && service >= 70 ? "games.ecommercerush.strong" : "games.ecommercerush.improve")}</p><button type="button" className="primary-action" disabled={paused} onClick={finish}>{t("games.ecommercerush.finish")} <BadgeCheck size={17}/></button></div>}
  </div></div>;
}

type PitchChoice = "homework" | "decor" | "snack" | "planner" | "app" | "poster" | "interviews" | "guess" | "trend";
type PitchAnswer = "specific" | "promise" | "avoid";

export function PitchBattle({ paused, onEnd }: SharedProps) {
  const { t } = useTranslation();
  const [stage, setStage] = useState<"build" | "questions" | "review">("build");
  const [choices, setChoices] = useState<Record<string, PitchChoice | null>>({ problem: null, solution: null, evidence: null });
  const [question, setQuestion] = useState(0); const [answers, setAnswers] = useState<PitchAnswer[]>([]);
  const complete = Object.values(choices).every(Boolean); const fit = (choices.problem === "homework" ? 30 : 8) + (choices.solution === "planner" ? 30 : 9) + (choices.evidence === "interviews" ? 27 : 7);
  const credibility = Math.min(100, 32 + (choices.evidence === "interviews" ? 30 : 7) + answers.filter((answer) => answer === "specific").length * 16);
  const clarity = Math.min(100, 34 + (choices.problem === "homework" ? 27 : 8) + (choices.solution === "planner" ? 22 : 7) + answers.filter((answer) => answer === "specific").length * 12);
  const pitchScore = Math.round((fit + credibility + clarity) / 3);
  const choose = (key: string, value: PitchChoice) => !paused && setChoices((current) => ({ ...current, [key]: value }));
  const answer = (value: PitchAnswer) => { if (paused) return; const next = [...answers, value]; setAnswers(next); if (question === 1) setStage("review"); else setQuestion(1); };
  const finish = () => onEnd({ achieved: pitchScore >= 61, score: pitchScore, stars: scoreStars(pitchScore), message: t("games.pitchbattle.result", { fit, credibility, pitchScore }) });
  const groups: { key: string; values: PitchChoice[] }[] = [{ key: "problem", values: ["homework", "decor", "snack"] }, { key: "solution", values: ["planner", "app", "poster"] }, { key: "evidence", values: ["interviews", "guess", "trend"] }];
  const prompts = ["need", "evidence"] as const;
  return <div className="game-stage venture-stage batch10-stage"><header className="game-play-header"><span className="game-play-header__icon"><Lightbulb size={20}/></span><div><p className="stage-kicker">{t("games.pitchbattle.objective")}</p><div className="stage-scoreline"><b>{t("games.pitchbattle.skill")}</b><span>{t("games.pitchbattle.stage")}</span></div></div></header><div className="venture-board"><div className="batch10-banner batch10-banner--pitch"><UsersRound/><div><span>{t("games.pitchbattle.title")}</span><b>{t("games.pitchbattle.stage")}</b></div></div>
    {stage === "build" && <div className="batch10-flow"><div className="batch10-customer-note"><Lightbulb size={18}/><p>{t("games.pitchbattle.story")}</p></div><div className="batch10-campaign-grid">{groups.map((group) => <section key={group.key}><p>{t(`games.pitchbattle.groups.${group.key}`)}</p><div className="batch10-mini-options">{group.values.map((value) => <button type="button" key={value} disabled={paused} onClick={() => choose(group.key, value)} className={choices[group.key] === value ? "batch10-mini-option batch10-mini-option--active" : "batch10-mini-option"}><b>{t(`games.pitchbattle.choices.${value}.title`)}</b><span>{t(`games.pitchbattle.choices.${value}.note`)}</span></button>)}</div></section>)}</div><div className="venture-metrics"><Metric label={t("games.pitchbattle.fit")} value={complete ? fit : "—"} positive={fit >= 65}/><Metric label={t("games.pitchbattle.evidence")} value={choices.evidence === "interviews" ? 86 : choices.evidence ? 42 : "—"} positive={choices.evidence === "interviews"}/></div><button type="button" className="primary-action" disabled={paused || !complete} onClick={() => setStage("questions")}>{t("games.pitchbattle.pitch")} <UsersRound size={17}/></button></div>}
    {stage === "questions" && <div className="batch10-flow"><div className="batch10-customer-note"><UsersRound size={18}/><p>{t(`games.pitchbattle.questions.${prompts[question]}.prompt`)}</p></div><section><p>{t("games.pitchbattle.answer")}</p><div className="batch10-choice-grid">{(["specific", "promise", "avoid"] as PitchAnswer[]).map((id) => <button type="button" key={id} disabled={paused} onClick={() => answer(id)} className="batch10-choice"><b>{t(`games.pitchbattle.answers.${prompts[question]}.${id}.title`)}</b><span>{t(`games.pitchbattle.answers.${prompts[question]}.${id}.note`)}</span></button>)}</div></section><div className="venture-metrics"><Metric label={t("games.pitchbattle.credibility")} value={credibility} positive={credibility >= 65}/><Metric label={t("games.pitchbattle.clarity")} value={clarity} positive={clarity >= 65}/></div></div>}
    {stage === "review" && <div className="venture-results"><p className="stage-kicker">{t(pitchScore >= 76 ? "games.pitchbattle.outcome.ready" : pitchScore >= 58 ? "games.pitchbattle.outcome.growing" : "games.pitchbattle.outcome.practice")}</p><div className="venture-metrics"><Metric label={t("games.pitchbattle.fit")} value={fit} positive={fit >= 65}/><Metric label={t("games.pitchbattle.credibility")} value={credibility} positive={credibility >= 65}/><Metric label={t("games.pitchbattle.clarity")} value={clarity} positive={clarity >= 65}/></div><p className="venture-insight">{t(pitchScore >= 70 ? "games.pitchbattle.strong" : "games.pitchbattle.improve")}</p><button type="button" className="primary-action" disabled={paused} onClick={finish}>{t("games.pitchbattle.finish")} <BadgeCheck size={17}/></button></div>}
  </div></div>;
}

type LaunchPhase = "discover" | "build" | "launch" | "grow" | "review";
type LaunchChoice = "tasks" | "trend" | "decor" | "learners" | "everyone" | "unknown" | "planner" | "hugeapp" | "poster" | "simple" | "featurepile" | "listen" | "guess" | "fair" | "free" | "high" | "helpful" | "hype" | "listenSales" | "pressure" | "steady" | "rushedOps" | "track" | "ignoreFinance" | "learnRivals" | "copyRivals" | "retain" | "chase";

const LAUNCH_STAGES: { phase: Exclude<LaunchPhase, "review">; groups: string[]; icon: typeof Rocket }[] = [
  { phase: "discover", groups: ["problem", "customer", "idea"], icon: Lightbulb },
  { phase: "build", groups: ["product", "feedback", "pricing"], icon: Box },
  { phase: "launch", groups: ["marketing", "sales", "operations"], icon: Megaphone },
  { phase: "grow", groups: ["finance", "competition", "growth"], icon: Rocket },
];

const LAUNCH_OPTIONS: Record<string, LaunchChoice[]> = {
  problem: ["tasks", "trend", "decor"], customer: ["learners", "everyone", "unknown"], idea: ["planner", "hugeapp", "poster"],
  product: ["simple", "featurepile"], feedback: ["listen", "guess"], pricing: ["fair", "free", "high"],
  marketing: ["helpful", "hype"], sales: ["listenSales", "pressure"], operations: ["steady", "rushedOps"],
  finance: ["track", "ignoreFinance"], competition: ["learnRivals", "copyRivals"], growth: ["retain", "chase"],
};

const STRONG_LAUNCH_CHOICES: LaunchChoice[] = ["tasks", "learners", "planner", "simple", "listen", "fair", "helpful", "listenSales", "steady", "track", "learnRivals", "retain"];

export function StartupLaunch({ paused, onEnd }: SharedProps) {
  const { t } = useTranslation();
  const [phase, setPhase] = useState<LaunchPhase>("discover");
  const [choices, setChoices] = useState<Record<string, LaunchChoice | null>>({});
  const active = LAUNCH_STAGES.find((step) => step.phase === phase);
  const stageIndex = LAUNCH_STAGES.findIndex((step) => step.phase === phase);
  const choose = (group: string, value: LaunchChoice) => !paused && setChoices((current) => ({ ...current, [group]: value }));
  const ready = active ? active.groups.every((group) => Boolean(choices[group])) : false;
  const dimension = (groups: string[]) => Math.round(groups.reduce((score, group) => score + (STRONG_LAUNCH_CHOICES.includes(choices[group] as LaunchChoice) ? 31 : choices[group] ? 11 : 0), 0) + 7);
  const customerScore = dimension(["problem", "customer", "idea"]); const productScore = dimension(["product", "feedback", "pricing"]); const launchScore = dimension(["marketing", "sales", "operations"]); const growthScore = dimension(["finance", "competition", "growth"]);
  const score = Math.round((customerScore + productScore + launchScore + growthScore) / 4);
  const advance = () => { if (!active || !ready || paused) return; if (stageIndex === LAUNCH_STAGES.length - 1) setPhase("review"); else setPhase(LAUNCH_STAGES[stageIndex + 1].phase); };
  const finish = () => onEnd({ achieved: score >= 58, score, stars: scoreStars(score), message: t("games.startuplaunch.result", { score, customerScore, productScore, launchScore, growthScore }) });
  const progressLabel = phase === "review" ? 4 : stageIndex + 1;
  return <div className="game-stage venture-stage batch10-stage"><header className="game-play-header"><span className="game-play-header__icon"><Rocket size={20}/></span><div><p className="stage-kicker">{t("games.startuplaunch.objective")}</p><div className="stage-scoreline"><b>{t("games.startuplaunch.skill")}</b><span>{t("games.startuplaunch.phase", { current: progressLabel, total: 4 })}</span></div></div></header><div className="venture-board"><div className="batch10-banner batch10-banner--launch"><Rocket/><div><span>{t("games.startuplaunch.title")}</span><b>{t("games.startuplaunch.capstone")}</b></div></div>
    {phase !== "review" && active && <div className="batch10-flow"><div className="batch10-customer-note"><active.icon size={18}/><p>{t(`games.startuplaunch.stageBrief.${phase}`)}</p></div><div className="batch10-campaign-grid">{active.groups.map((group) => <section key={group}><p>{t(`games.startuplaunch.groups.${group}`)}</p><div className="batch10-mini-options">{LAUNCH_OPTIONS[group].map((value) => <button type="button" key={value} disabled={paused} onClick={() => choose(group, value)} className={choices[group] === value ? "batch10-mini-option batch10-mini-option--active" : "batch10-mini-option"}><b>{t(`games.startuplaunch.choices.${value}.title`)}</b><span>{t(`games.startuplaunch.choices.${value}.note`)}</span></button>)}</div></section>)}</div><div className="venture-metrics"><Metric label={t("games.startuplaunch.customer")} value={customerScore} positive={customerScore >= 70}/><Metric label={t("games.startuplaunch.product")} value={productScore} positive={productScore >= 70}/><Metric label={t("games.startuplaunch.launchScore")} value={launchScore} positive={launchScore >= 70}/><Metric label={t("games.startuplaunch.growthScore")} value={growthScore} positive={growthScore >= 70}/></div><button type="button" className="primary-action" disabled={paused || !ready} onClick={advance}>{stageIndex === 3 ? t("games.startuplaunch.review") : t("games.startuplaunch.nextPhase")} <Rocket size={17}/></button></div>}
    {phase === "review" && <div className="venture-results"><p className="stage-kicker">{t(score >= 78 ? "games.startuplaunch.outcome.ready" : score >= 60 ? "games.startuplaunch.outcome.growing" : "games.startuplaunch.outcome.rebuild")}</p><div className="venture-metrics"><Metric label={t("games.startuplaunch.customer")} value={customerScore} positive={customerScore >= 70}/><Metric label={t("games.startuplaunch.product")} value={productScore} positive={productScore >= 70}/><Metric label={t("games.startuplaunch.launchScore")} value={launchScore} positive={launchScore >= 70}/><Metric label={t("games.startuplaunch.growthScore")} value={growthScore} positive={growthScore >= 70}/></div><div className="batch10-capstone-card"><Flag size={22}/><div><b>{t("games.startuplaunch.capstone")}</b><p>{t("games.startuplaunch.capstoneHint")}</p></div></div><p className="venture-insight">{t(score >= 68 ? "games.startuplaunch.strong" : "games.startuplaunch.improve")}</p><button type="button" className="primary-action" disabled={paused} onClick={finish}>{t("games.startuplaunch.finish")} <BadgeCheck size={17}/></button></div>}
  </div></div>;
}
